dist: trusty
language: php
branches:
  only:
  - master
  - "/^[[:digit:]]+\\.[[:digit:]]+\\.[[:digit:]]+.*$/"
matrix:
  fast_finish: true
  include:
  - php: 7.2
    env: DEPENCENCIES=highest
  - php: 7.2
sudo: false
cache:
  directories:
  - "$HOME/.composer/cache"
script:
- composer test
after_success:
- travis_retry php vendor/bin/php-coveralls -v
before_deploy:
- composer phar:install-tools
- composer install --prefer-dist --no-dev --no-interaction
- composer phar:build
deploy:
  provider: releases
  api_key:
    secure: QGkHkF4wJnMdXsNrxQapOxiK0gW7EIFzZL2AI17cWdY6l/q5n7+xncQBWDeNlGyBWGiHx7c9VJh55+BTti/KYE0z4NSBFDVVNcTy3dzhdbNu0FVWzuVFvw1rt7pzhzS6jXWr/9VuCZAAfBCwvooT71eZe6BuWzkL3O0iNWBtVTtnz/Z2DMl8Ob2nuUv4RmaseOLB/q02G6eVX6OlRa/KCl5Xrix0I5MewaD8W/iGHN4+1QtZwRT1XjWvwsf2Nm23Xst6DUigctPNoiEWxv4DfIIr33K8T6KkWbi6l10525LYr/2rhSjaXTD0UUCUZFBehPa/XgMqSNYv7nZNLhGTSE+p7kGIZPoG9vtV0OO6di8TVvaFU1/Pi8T8NPSgeDzPpkhspjm51zjJBJqBSOhyu63QdGOXDmofnihDVNLozlR5j0DJ30mSrVUediSjEP08rkg018p4QAJM8x3b4kOhUpTU8EB+94OS+fVm8UqztsTj2lFErUuxPLXqj8h0L8asP2sqq9zLkB3raZrxrQPfse4xgTUmw0STACmWwPFlWmjB2+teRp8zZOJ5mo7i1Dlhjolxy4hZnSNNLWsBrcrEnV5BY6VcBEKjjVlAvj3LriaBxku+Py0P151nwQUJXbEpml1WI5kKseQmjlYpus5m4p9Z7x60IC+uxTvv4GXjHo8=
  file: diffy.phar
  on:
    repo: DiffyWebsite/diffy-cli
